### ISSUE TITLE
Done!

### ISSUE THREAD

**Issue by Twitti** [Twitti/PatronTasks#1]
I finished my work. And I think problems with git will 
never afraid me again.
I created new repository, and organise files as good as I can...)
I want to work in this repo

**Comment by parfeniukink** [comment]
Ok.
Delete another repo. But this repo is not good to.
Don't delete it! But remember, if u wanna to create the second branch, u need to knaw **marging** !
And the next - **I'll tell u about branches**, So do your work **in this repo** in **master**.
U create branche, if u trying to make global function in application. Or in start as u do. But don't do this now !
**And the last**. Why did you do commits for everything. One my task = 1 your commit.
Your commits have the same names. It's to hard to understand other people with u're project.
And the last-last. Your variables are terrible ! Crypton **text** = new Crypton(). _object must have the same name with class!_ And the last. It's so bad logic. U created **useful** variable in Crypton class.
And.... Why **source** ? Maybe cryptography folder ? I think so...
So close this issue and look what you need to do in next issues.
