### ISSUE TITLE
Wishes

### ISSUE THREAD

**Issue by Twitti** [Twitti/PatronTasks#7]
I did my work, and I'm waiting for new tasks. I know that the programming it's **very extensive part** of Computer Sience. What I want to do?
1) You give me task, give maybe some recommends and I would like to know what awaits me in the next task (it's like do that, that. that, correct that, read about that, if you handle with averything read or do that, about that...)
2) I want to listen your recomends not only about programming ( **Math, English, things in computer architecture**...)
3) I think it will be great if you gave me a weekly assignment. I would work on for a week. It is not necessary that you check or participate there somehow. I also understand this all the time, which I would not want to take. I arrange myself like this, but I would not like to do something not useful.
Thaks))

**Comment by parfeniukink** [comment]
Ok, i give U easy task, couse I need to understand you skills for the start

**Comment by parfeniukink** [comment]
I can send U different IT-posts from forums if U want too.
do not jump before you're pushed (_не біжи поперед батька в пекло_) -> перший фразеологізм )
